INSERTION_MARK = b"+"
DELETION_MARK = b"-"
REPLACEMENT_MARK = b"%"
REPLACEMENT_SPLIT_MARK = b"$"
INDEX_PAYLOAD_SEPERATOR_MARK = b"|"
UNMARK_MARK = b"\\"
INT_TO_BYTE_CONVERSION_CONST = 48

SAFE_MARKS = [
    UNMARK_MARK,  # This has to be the first
    INSERTION_MARK,
    DELETION_MARK,
    REPLACEMENT_MARK,
    REPLACEMENT_SPLIT_MARK,
    INDEX_PAYLOAD_SEPERATOR_MARK,
]

REGULAR_MARKS = [
    INSERTION_MARK,
    DELETION_MARK,
    REPLACEMENT_MARK,
    REPLACEMENT_SPLIT_MARK,
    INDEX_PAYLOAD_SEPERATOR_MARK,
]

ENCODING = "utf-8"