INSERTION_MARK = "+"
DELETION_MARK = "-"
REPLACEMENT_MARK = "%"
REPLACEMENT_SPLIT_MARK = "$"
INDEX_PAYLOAD_SEPERATOR_MARK = "|"
UNMARK_MARK = "\\"
SAFE_MARKS = [
    UNMARK_MARK,  # This has to be the first
    INSERTION_MARK,
    DELETION_MARK,
    REPLACEMENT_MARK,
    REPLACEMENT_SPLIT_MARK,
    INDEX_PAYLOAD_SEPERATOR_MARK,
]

REGULAR_MARKS = [
    INSERTION_MARK,
    DELETION_MARK,
    REPLACEMENT_MARK,
    REPLACEMENT_SPLIT_MARK,
    INDEX_PAYLOAD_SEPERATOR_MARK,
]
